- src/locales/nl.ts
> Add Dutch localization

- src/locales/nl.ts
Update Dutch Translations
Translations were outdated
> Update Dutch Translations

- src/locales/en.ts
- src/locales/nl.ts
Updated Dutch translations and fixed a typo inside the English localization
> Update Dutch Translations and fixed typo for English localization

- data/preset/entity/bee/manifest.json
- package.json
- src/appVersion.json
- src/components/Projects/CreateProject/CreateProject.vue
- src/components/Windows/Project/CreatePreset/CreatePreset.ts
- Fixed lang files not being created properly
- Fixed infinite loading spinner upon creating first project
> v2.0.0-alpha.4

- data/packages/minecraftBedrock/preset/block/ore/feature.json
- data/packages/minecraftBedrock/preset/block/ore/featureRule.json
- data/packages/minecraftBedrock/preset/item/armor/attachableChestplate.json
> fixed ore and armour presets 

- src/components/App/Vue.ts
- src/locales/zhTW.ts
- src/locales/zh_tw.ts
Add Traditional Chinese translation(zh_tw.ts).
Adding Traditional Chinese translation will make it easier for players in Taiwan to develop Add-Ons.
> Add Traditional Chinese Translation

- src/components/Extensions/Scripts/Modules/project.ts
The `compileFiles` function can be imported from the `@bridge/project` extension module to update and compile specific files
> feat: add compileFiles function to @bridge/project

- src/components/Compiler/Worker/Plugins/CustomComponent/Component.ts
This is a relatively small feature that introduces the option to override the merge behaviour of the create function in the custom component core extension. The function signature is `(deepMerge: (oldData: any, newData: any) => any, oldData: any, newData: any) => any`. It receives the default `deepMerge` function to, for example, allow normal behaviour to be resumed.
This update also includes typings and documentation which are in their respective pull requests. A minor typing and documentation fix is also included to bring them into agreement with the implementation of the create function.
I was looking for a way to override data at a location and the hack I was using didn't work in the case of lists.
> feat(Custom Component): optional merge arg in create

- src/locales/ja.ts
Corrected unnatural Japanese translations and unified the long sound notation of words.
It will help you understand the function better.
> Updated Japanese translation

- src/locales/zhCN.ts
update `functionValidator` part and format some former syntax
Mainly updated `functionValidator` part of `zhCN.ts`.
Follow the Function Validator update. And fix some syntax in former texts.
> Make `functionValidator` of `zhCN.ts` up to date

- src/locales/zhCN.ts
Update zh_CN TargaAction Locale and a Word Translation Err.
Update Localization.
> upd: Update zh_CN TargaAction Locale & a Word Err

- src/locales/zhCN.ts
zh_CN locale with Wild Update & manifest missing err strings
> upd: zh_CN locale with Wild Update & manifest missing err strings

- src/components/Languages/Mcfunction/Validation/Validator.ts
- src/locales/ja.ts
Added wild update and Function Validator to Japanese translation
> upd: ja_JP add wild update and Function Validator

- src/locales/ja.ts
Added Japanese Translation for upgrade virtual FS to real FS.
> upd: ja_JP upgrade FS Translation

- src/locales/zhCN.ts
Update zh_CN strings of com.mojang setup instructions and real File System upgrades, and fix some translation typos
> upd: zh_CN com.mojang setup & real FS strings

- src/locales/ja.ts
Added Japanese Translation for around compiler settings (Watch mode, etc.)
Unified word representation
> upd: ja_JP Add watch mode translations

- src/locales/ja.ts
Added translations for features added/changed so far in dev branch
> upd: Additional Japanese translation

- .vscode/launch.json
Created `.vscode/launch.json` configurations for Edge and Chrome to enable debugging in VS Code. This will add "Debug in Chrome" and "Debug in Edge" options to VS Code's Run and Debug configurations.
**Docs:** https://code.visualstudio.com/docs/editor/debugging#_launch-configurations
Having a debugger configuration ready will make development easier for contributors.
> feat: VS Code Debug Configuration

- src/locales/zh-CN.json
Update zh_CN locales to v2.3.3 latest version
> upd: Update zh_CN locales to v2.3.3 latest version

- src/components/UIElements/DirectoryViewer/ContextMenu/Actions/Refresh.ts
- src/components/UIElements/DirectoryViewer/ContextMenu/Folder.ts
- src/locales/en.json
Allow users to refresh specific folders within the DirectoryViewer
> feat(DirectoryViewer): refresh folder

- src/components/FileSystem/FileSystem.ts
Part of an effort to optimize project imports
> upd: faster directory copying

- src/components/ImportFile/ZipImporter.ts
- src/components/Projects/Import/fromBrproject.ts
- src/components/Projects/Import/fromMcaddon.ts
- src/components/Projects/Import/fromMcpack.ts
Fixes an issue with project imports on devices using the file system polyfill. Closes #600
> fix: project imports

- src/components/Editors/Sound/SoundTab.ts
- src/components/Editors/Sound/SoundTab.vue
- src/components/TabSystem/TabProvider.ts
- src/utils/disposableListener.ts
Allow users to play ".ogg" and ".mp3" files with bridge.
Closes #100
> feat: sound player

- src/components/Editors/EntityModel/Tab.ts
- src/components/Editors/EntityModel/create/fromClientEntity.ts
- src/components/Editors/EntityModel/create/fromEntity.ts
- src/components/Editors/EntityModel/create/fromGeometry.ts
- src/components/Windows/Common/Dropdown/Dropdown.vue
- src/components/Windows/Common/Dropdown/DropdownWindow.ts
- src/locales/en.json
Allows users to preview any geometry file by manually selecting a texture for the model.
> feat: display models without client entity

- src/components/Editors/Sound/SoundTab.ts
> fix: sound keeps playing upon closing tab

- src/components/FileSystem/Zip/StreamingUnzipper.ts
- src/components/FileSystem/Zip/Unzipper.ts
- src/components/ImportFile/ZipImporter.ts
- src/components/Projects/Import/fromBrproject.ts
- src/components/Projects/Import/fromMcaddon.ts
- src/components/Projects/Import/fromMcpack.ts
The new streaming unzipper is slightly faster and consumes less memory. This PR switches all of our codes over from the legacy `Unzipper` class to the new `StreamingUnzipper`.
> upd: use streaming unzipper

- src/components/Editors/TreeEditor/Tab.vue
- src/components/Editors/TreeEditor/TreeEditor.ts
- src/components/Editors/TreeEditor/TreeSelection.ts
- src/components/JSONSchema/Schema/Items.ts
- src/components/JSONSchema/Schema/Schema.ts
- src/components/Windows/Settings/setupSettings.ts
Finally fixes tree editor arrays to work correctly.
- closes #572 
- closes #582 
- closes #673
> fix(TreeEditor): arrays now work properly

- src/components/ContextMenu/ContextMenu.ts
- src/components/ContextMenu/ContextMenu.vue
- src/components/ContextMenu/showContextMenu.ts
- src/components/Editors/TreeEditor/Tab.vue
- src/components/Editors/TreeEditor/TreeEditor.ts
- src/components/Editors/TreeEditor/TreeSelection.ts
- src/components/JSONSchema/Manager.ts
- src/components/JSONSchema/Registry.ts
- src/components/JSONSchema/Schema/Items.ts
- src/components/JSONSchema/Schema/Root.ts
- src/components/JSONSchema/Schema/Schema.ts
- src/components/Windows/Settings/setupSettings.ts
**Depends on #716** 
Show documentation from our JSON schemas (titles & descriptions) within the tree editor context menu when available.
> feat(TreeEditor): show schema docs

- src/components/UIElements/DirectoryViewer/DirectoryView/DirectoryView.vue
- src/components/Windows/Settings/setupSettings.ts
- src/locales/en.json
> feat: configure folder indentation

- src/components/UIElements/DirectoryViewer/Common/Name.vue
> fix: rename files on mobile

- src/components/FileSystem/FileSystem.ts
- src/components/PackExplorer/HomeView/HomeView.vue
- src/components/PackExplorer/HomeView/ImportOldProjects.vue
- src/components/PackExplorer/HomeView/SetupView.vue
- src/locales/en.json
Allow users to easily import old projects.
Importing all projects at once was sadly too slow
> feat(tauri): import projects

- src/components/UIElements/DirectoryViewer/ContextMenu/Actions/OpenWith/Snowstorm.ts
This PR properly enables "Open with Snowstorm". We previously didn't implement loading the connected particle texture
> feat: open with snowstorm

- src/components/Compiler/Window/OutputFolders.vue
- src/components/FileSystem/Pickers/showFolderPicker.ts
- src/components/ImportFolder/ImportProjects.ts
- src/components/PackExplorer/HomeView/ImportOldProjects.vue
- src/components/Projects/ProjectManager.ts
- src/components/Toolbar/Category/file.ts
- src/locales/en.json
Allow importing more than one project at once. Also tweaked locale message a bit to make sure that the information window tells why a project failed to import and which one failed
> feat: import multiple projects

- src/components/TabSystem/WelcomeScreen.vue
- src/locales/en.json
Adds a dedicated button for downloading our native app to the WelcomeScreen
> feat: download native app button

- src/components/PackExplorer/HomeView/SetupHint.vue
- src/components/PackExplorer/HomeView/SetupView.vue
- src/components/UIElements/Sheet.vue
- src/components/Windows/InformedChoice/InformedChoice.vue
- src/locales/en.json
- Point users to a version of com.mojang syncing that will definitely work
- Rework editor setup to be less weird. Options didn't feel connected to the description before
> upd: new setup flow

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
This PR bumps Tauri to its latest version
> upd: tauri to v1.2.2

- src-tauri/src/main.rs
Automatically open dev tools on debug builds.
> upd: auto open devtools

- src/components/App/Tauri/TauriUpdater.ts
- src/components/Windows/Error/ErrorWindow.tsx
- src/components/Windows/Update/UpdateWindow.tsx
- src/locales/en.json
This new window opens whenever a new update is available to drive more awareness towards available updates. This should hopefully help our users to update more regularly.
closes #832
> feat: update window

- src/components/BottomPanel/BottomPanel.vue
- src/components/Solid/Inputs/Button/SolidButton.tsx
- src/components/Solid/Window/Window.tsx
- src/components/Windows/Error/ErrorWindow.tsx
- tailwind.config.js
> feat(SolidWindows): now respect user themes

- package.json
- src/components/FileSystem/FileSystem.ts
- src/components/FileSystem/Polyfill.ts
- src/components/TabSystem/TabSystem.ts
- src/components/UIElements/DirectoryViewer/DirectoryView/DirectoryView.vue
- Importing folders now works properly on the native build (1e50fbc0918d48c11574d238a0fd30565042a7cb)
- Fixed an error that would occur on opening files (dcf3e52c24126837eb6849c38ea49dbeae692e7c)
> Critical Fix v2.6.3

- src/components/TabSystem/TabSystem.ts
- src/components/Toolbar/Category/view.ts
Feature #892
Switch tab bug #933 need fixes before
To test this feature:
- Open some file in a project before test
- Open Settings
- Find "Next Tab"
- Click on fire
> feat: ctrl + tab switch to recent selected tab

- public/changelog.html
- src-tauri/src/watch.rs
https://discord.com/channels/602097536404160523/1172477965938999357
> Hot fix custom bridge folder on native crashing

- package.json
> Reverse bump

- src/locales/ko.json
Added all 1000+ missing Korean translations.
> Update Korean translation to the latest version

- src-tauri/tauri.conf.json
- src/components/Editors/Text/TextTab.ts
- src/components/Editors/TreeEditor/Tab.ts
- src/components/Windows/Error/ErrorWindow.tsx
> Japanese Translations + Fix Native Clipboard
