bridge-core/editor

src/components/Projects/CreateProject/Files/Lang.ts, src/components/Projects/CreateProject/Files/Manifest.ts
This PR adds the following:
- Create the languages.json file for new projects with `en_US` as entry.
- Add `min_engine_version` to the Rp manifest. This is needed to make sure the pack shows up inside Minecraft.
- I also changed 1.13.0 back to the target version selected, because this should be the version you are developing against.
These changes are needed to show the packs properly inside Minecraft.
=> Fix manifest generation and add languages.json to new projects

src/components/Windows/Project/CreatePreset/PresetWindow.ts, src/components/Windows/Project/CreatePreset/PresetWindow.vue
- Added an optional `multiple` boolean value to the `IPresetFieldOpts` interface.
- Added a corresponding `multiple` prop to the Preset Window's `v-file-input`
Modified the project presets window to accept multiple files in the file input. Setting the file input field's new `multiple` option to `true` will add the `multiple` prop to the field's `v-file-input`. An array of `File` objects is passed to the preset script.
Presets documentation will need to be updated.
This is a minor change which will allow more options for bridge. preset authors. I personally intend to use it in upcoming changes to the Texture Set Generator extension.
=> feat: Added "multiple" file input option to Presets Window

src/components/Windows/Project/CreatePreset/PresetWindow.ts
Changed default value of shouldReloadPresets to true to initialize state of new preset window instance
If set to false state of preset window returns an empty object causing undefined errors when user tries to add a new file to the project where after the app freezes completely.
Refer to issue #67 and #68
=> fix: new file error

src/locales/zhCN.ts
Localizations for the new compiler window, watch mode, profile, valid project name, and version increment in zh-CN, with some corrections.
=> upd: zh-CN localizations for compiler and so on

src/components/Projects/CreateProject/Files/RP/SoundDefinitions.ts
Add the `format_version` object for `sound_definitions.json` files created with projects. `1.14.0` is the format version used in the vanilla _Minecraft_ file and is supported in the latest stable and preview versions.
_Minecraft_ doesn't read `sound_definitions.json` without a format version.
=> upd: update SoundDefinitions.ts

src/components/Data/RequiresMatcher/RequiresMatcher.ts
Currently, projects without a targetVersion fail to load various of our app features correctly because we don't fallback to the latest Minecraft release correctly. This also resulted in users being unable to open the "New File" window within these projects.
Also, maybe this should instead load the current stable release instead, @Joelant05?
=> fix: fallback to latest Minecraft release correctly

src/components/OutputFolders/ComMojang/ComMojang.ts, src/components/Projects/ProjectChooser/ProjectChooser.ts
Previously, the button did not appear if permissions to the com.mojang folder weren't granted yet
=> upd(ProjectChooser): load all projects button now also works for com.mojang projects

src/components/Windows/ExtensionStore/ExtensionCard.vue, src/components/Windows/ExtensionStore/ExtensionViewer.ts
This PR changes the extension card viewer to always show the names of compiler plugins within the extension. Previously, this UI only showed up for installed extensions after closing & then re-opening the extension store.
=> feat: always show available compiler plugin names

src/components/Mixins/AppToolbarHeight.ts, src/components/Sidebar/Button.vue, src/components/Sidebar/Sidebar.vue, src/components/Toolbar/Main.vue
The toolbar on mobile was pretty useless since the last release because it only showed the "Actions" item and the bridge. logo.
This PR hides the toolbar on mobile and instead integrates the toolbar items into the sidebar freeing up more space on small screens.
- Should we show a bridge. logo within the sidebar? (Yes, above all buttons?)
- Where should we display the bridge. version number? (Bottom of the sidebar?)
=> feat: no mobile toolbar

src/components/OutputFolders/ComMojang/ComMojang.ts, src/locales/en.json, src/locales/ja.json, src/locales/nl.json, src/locales/zh-CN.json, src/locales/zh-TW.json
Previously, an additional confirmation window popped up after choosing the "Output Folder" option within the InformedChoiceWindow. This window is entirely unnecessary now that the InformedChoiceWindow exists after dropping a folder onto bridge. so we should remove it to reduce friction around setting up the com.mojang folder
=> upd(ComMojang): remove double prompt

src/components/Windows/ExtensionStore/ExtensionActions.ts, src/components/Windows/ExtensionStore/ExtensionViewer.ts
Installing extensions locally to the virtual project that backs the HomeView is not desirable behavior.
=> upd(Extensions): only allow global installations on HomeView

src/components/TabSystem/CommonTab.ts, src/components/TabSystem/TabSystem.ts, src/components/Toolbar/Category/view.ts, src/locales/en.json
Provide users with quick actions for switching between tabs without using a mouse. Closes #54.
=> feat: tab switching actions

src/components/Editors/Text/TextTab.ts, src/components/Editors/TreeEditor/Tab.ts, src/components/Editors/TreeEditor/TreeEditor.ts, src/components/TabSystem/FileTab.ts, src/components/Windows/Settings/setupSettings.ts, src/locales/en.json
This implements an auto save setting. When it is enabled, bridge. will automatically save all unsaved changes to files after a 3s delay.
I consider auto saving an important feature to improve the experience using bridge. on mobile as saving files isn't something users are used to do manually on these platforms (that's why the setting is on by default for mobile users). In the past, bridge. not automatically saving changes has been a source of constant confusion for our users.
=> feat: auto save setting

src/components/FileSystem/saveOrDownload.ts
I cannot test it myself but this _might_ fix the bug where Chrome appended ".txt" to every project export.
=> fix: wrong file extension on export

src/components/Windows/Layout/BaseWindow.vue
Windows shouldn't be rounded on mobile as they're fullscreen by default.
=> fix: rounded windows on mobile

src/components/Common/GlobalMutex.ts, src/components/Common/Mutex.ts, src/components/FileSystem/Virtual/DirectoryHandle.ts, src/components/FileSystem/Virtual/FileHandle.ts
This fixes the currently common problems with projects not exporting correctly. The root issue likely caused a bunch of other critical bugs we didn't notice yet.
At least one issue that was likely connected to this problem is #529 but it's also likely that people complaining about the inability to import the ".mcaddon" file into Minecraft experienced this problem in the past (e.g. manifest file not exported).
=> fix: project exports

src/components/Windows/Settings/setupSettings.ts
While bridge. predictions remain broken (#582, #572), disable them by default for users using the tree editor.
=> fix: turn bridge. predictions off by default

src/components/Actions/KeyBindingManager.ts
This PR internally allows us to bind actions to mouse buttons by using keybinding strings like `Ctrl + mouseBack`.
Towards #54
=> feat: mouse keybindings

src/components/Compiler/Sidebar/create.ts, src/components/FileSystem/saveOrDownload.ts, src/components/Sidebar/SidebarElement.ts, src/components/Sidebar/setup.ts, src/locales/en.json
Disable the compiler window by default on mobile and add a new quick export action to users which cannot use com.mojang syncing
closes #654
=> feat: quick exports

src/components/Projects/Export/AsBrproject.ts
This PR adds an unlink call to delete previously exported ".brproject" packages before doing a new export. This prevents the ".brproject" package growing in size even though the project itself doesn't change
=> fix: unlink previous brproject file before export

src/components/Projects/Import/fromBrproject.ts, src/components/Projects/Import/fromMcaddon.ts, src/components/Projects/Import/fromMcpack.ts, src/components/UIElements/DirectoryViewer/ContextMenu/Actions/Edit/Paste.ts, src/utils/directory/findSuitableName.ts, src/utils/directory/getEntries.ts
We now use the same logic for finding a free project name that is also used for pasting files and folders.
=> fix: import overwrites existing projects

src/components/ImportFile/BBModel.ts
Blockbench's bbmodel animation format appears to support omitting `"type": "bone"`. This aligns bridge.'s behavior so we also support importing animators without a set type correctly
=> fix(bbmodel): animation imports

src/App.vue, src/components/CommandBar/CommandBar.vue, src/components/Mixins/AppToolbarHeight.ts, src/components/TabSystem/CommonTab.ts, src/components/TabSystem/TabActions/ActionBar.vue, src/components/TabSystem/TabBar.vue, src/components/TabSystem/TabContextMenu/Fullscreen.ts, src/components/Toolbar/Category/view.ts, src/locales/en.json
This PR introduces a new fullscreen mode for tabs which hides all UI elements except for the tab bar and the tab contents. This is great for focusing on editing files and can also give embedded third party tools more space to work with
closes #683
=> feat: full screen tab mode

package-lock.json, package.json, src/components/Editors/IframeTab/API/IframeApi.ts
Connecting the iframe API was racy before because there was no guarantee for the connection event listener to be setup before the iframe posted its message port. This PR bumps `bridge-iframe-api` to fix this behavior, see https://github.com/bridge-core/bridge-iframe-api/compare/01162de..7786717#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3d
=> fix: unreliable iframe connection

src/components/FileSystem/Zip/ZipDirectory.ts
ZIP directories in parallel and allow the package method to specify folders to ignore from the output ZIP
=> upd: faster directory zipping

src/components/FileSystem/Zip/ZipDirectory.ts, src/components/Projects/Export/AsBrproject.ts
The `builds/` folder is producing unnecessary bloat within the brproject package as we currently essentially store the same pack three times (main pack, dev output and dist output).
Depends on #698
=> upd: omit builds folder

src/components/FileSystem/Zip/StreamingUnzipper.ts, src/components/Projects/Import/fromBrproject.ts
Switch the ".brproject" unzipping to use a streaming unzipper to make the process faster and use less memory.
This should fix the issue [described here](https://discord.com/channels/602097536404160523/1035399371333840916/1035399371333840916). If this change is successful, we should further investigate switching ".mcaddon" and ".mcpack" importers over too.
=> feat: streaming unzipping

vite.config.ts
This PR adjusts our service worker to properly cache icon fonts and wasm files so bridge. works offline correctly.
closes #692
=> fix: bridge. offline experience

src/components/Editors/TreeEditor/Tab.vue
Some users cannot add arbitrary values within the tree editor because the virtual keyboard doesn't show the correct action button.
https://discord.com/channels/602097536404160523/1033955787028049960
=> fix(TreeEditor): add enterkeyhint

src/components/FileDropper/FileDropper.ts
Up until now, it wasn't possible to link the com.mojang folder while the linking instructions within the compiler window are visible. This change enables file/folder drop handlers while windows are opened
=> fix: make file/folder dropping possible while windows are visible

src/components/FileSystem/Virtual/Stores/IndexedDb.ts
Fixes an issue where the virtual file system could save duplicated entries representing the same file or folder. This was caused by our legacy format interfering with the new format (Set deduplication doesn't work when one entry is of type string and the other is an object)
=> fix: duplicated entries within virtual fs

src/components/FileSystem/Virtual/Stores/IndexedDb.ts
#740 changed the internal storage format for files and directories. This broke loading of older projects on our file system polyfill platforms (e.g. mobile iOS) with the latest nightly build.
Root issue was that an `Uint8Array` returns `false` when being passed to the `Array.isArray(...)` method. Replacing this condition with an `instanceof` check against the `Uint8Array` class does the trick. (TypeScript actually caught this issue but I thought I was smarter and type casted `rawData` instead. This isn't necessary anymore too)
=> fix(IndexedDb): format compat

src-tauri/src/main.rs, src/components/FileSystem/Virtual/FileHandle.ts, src/components/FileSystem/Virtual/Stores/BaseStore.ts, src/components/FileSystem/Virtual/Stores/IndexedDb.ts, src/components/FileSystem/Virtual/Stores/TauriFs.ts
Up until now, our file system polyfill did not properly support the `lastModified` timestamp on File objects. (#664)
I've already made some changes to the Memory and IndexedDB backing fs stores to eventually support this with (#740), this PR now enables proper support for the `lastModified` timestamp for all available backing stores of our fs polyfill (TauriFS, IndexedDB and Memory).
Practically, this means that the pack indexer can once again detect when a file did not change and Dash can skip work upon selecting a project if no files changed.
Closes #664
=> upd: use last modified timestamp

src-tauri/src/fs_extra.rs, src-tauri/src/main.rs, src/components/FileSystem/FileSystem.ts
Make copying directories significantly faster on our Tauri builds by calling into Rust.
You can test these changes by using the "Import Projects" button. [Comment out the fast path here to test the previous implementation.](https://github.com/bridge-core/editor/pull/761/files#diff-f5dd2dd597f52c18e9dadbee4d919ef36a025ad612608d056b901befa4b8fea9R285-R298) Make sure to select a sufficiently large project.
I am seeing more than 230x faster directory copies on my benchmarks
=> feat: fast directory copying

src/components/TabSystem/TabBar.vue, src/components/TabSystem/TabSystem.ts
The inactive tab system once again displays properly. This was apparently broken for some time now because the _isActive property wasn't reactive.
=> fix: inactive tab display

src/components/Data/DataLoader.ts, src/components/FileSystem/Fast/getDirectoryHandle.ts, src/components/FileSystem/FileSystem.ts, src/components/FileSystem/Virtual/DirectoryHandle.ts, src/components/FileSystem/Virtual/FileHandle.ts, src/components/FileSystem/Virtual/Handle.ts, src/components/FileSystem/Virtual/getParent.ts, src/components/FileSystem/Virtual/pathFromHandle.ts
Skip most of the internal implementation of the virtual file system polyfill on Tauri builds to make `getDirectoryHandle` use a constant single fs interaction instead of one fs interaction per path segment.
Reading a nested texture file within a RP is up to 2x faster now. Exact improvement depends on the path length.
**Edit:** I have also pushed a commit with a fast path for IndexedDB based virtual directory handles now. Results aren't as impressive as I've hoped them to be but I am still seeing a 1s reduction (from 6s) to load a file on my benchmark.
=> feat: fast path for getDirectoryHandle

src/components/Editors/ThreePreview/ThreePreviewTab.ts, src/components/Projects/Project/Project.ts, src/components/TabSystem/TabBar.vue
closes #766 and related issues that originated in switching _isActive over to a `Ref<boolean>`
=> fix: openInSplitScreen

src/App.ts, src/components/Extensions/Scripts/Modules/utils.ts, src/components/Toolbar/Category/help.ts, src/components/Windows/Socials/Main.vue
Opening an URL via `window.open()` is currently broken on MacOS on our native build. This fixes the issue by using Tauri's API for opening URLs instead
=> fix: open url

src/components/TabSystem/WelcomeScreen.vue, src/components/WelcomeAlert/Alert.vue
Padding for the remote alert wasn't working correctly before this PR. This affected the app states when sidebar content is hidden and when the sidebar nav is hidden (mobile).
=> fix: remote alert padding

src/components/Projects/Import/fromBrproject.ts, src/components/Projects/Import/fromMcaddon.ts, src/components/Projects/Import/fromMcpack.ts, src/components/Toolbar/Category/file.ts, src/components/Toolbar/Category/project.ts, src/components/Windows/Settings/setupSettings.ts
There were still a lot of references to "isUsingFileSystemPolyfill" that didn't make sense anymore for the native MacOS app leading to unexpected behavior such as prompts for deleting the current project after a project import.
=> fix: various conditions for tauri app

src/components/FileSystem/Zip/StreamingUnzipper.ts, src/components/Projects/Import/fromBrproject.ts, src/components/Projects/Import/fromMcaddon.ts, src/components/Projects/Import/fromMcpack.ts, src/components/Toolbar/Category/file.ts, src/components/Toolbar/Category/project.ts, src/components/Windows/Settings/setupSettings.ts, src/utils/iterateDir.ts
.mcaddon & .mcpack imports where broken because of three reasons:
1) Invalid creation of paths (`projects/myProject/./RP` instead of `projects/myProject/RP`); fixed by using path.join(...) (https://github.com/bridge-core/editor/compare/dev...fix/project-imports?expand=1#diff-949e05b954a361351c598f5d8afbb4bcdd68e9cb63cafbb415a09472117ac807R106)
2) The streaming unzipper tried to write directory paths as files (https://github.com/bridge-core/editor/compare/dev...fix/project-imports?expand=1#diff-a23bb193ef8cc693b41127c17e80b5a3815b9730e55cf1aee08620dad17477ebR28)
3) Chromium's writable close(...) method apparently doesn't properly await the file content being transferred from the ".crswap" file to the actual file. We're doing two things now to prevent an error:
- Do not iterate over …
=> fix: project imports

src/components/BottomPanel/Terminal/Terminal.ts, src/components/FileSystem/saveOrDownload.ts, src/components/UIElements/DirectoryViewer/ContextMenu/Actions/RevealInFileExplorer.ts, src/components/Windows/Settings/SettingsWindow.ts, src/components/Windows/Settings/setupSettings.ts, src/locales/en.json, src/utils/getBridgeFolderPath.ts, src/utils/getStorageDirectory.ts
Makes the "Select Root Folder" button work on our native build and adds an additional "Reset Root Folder" button on our native build if a different root folder is configured.
closes #788
=> feat: configure bridge folder

src/components/Extensions/Scripts/Modules/import.ts
Adds an extension API to open a directory picker. In order to fully close the issue linked below, the Vanilla Pack Viewer needs to be updated with a button to open the directory picker.
towards #789
=> feat: add API to open directory picker

src-tauri/tauri.conf.json, src-tauri/tauri.windows.conf.json
This fixes dropping files onto bridge. on our native app on MacOS. (Tauri's file drop event seems to disable the webview's native events which our codebase is already using)
Please confirm that this also fixes the problem on Windows during review.
closes #793
=> fix: file dropping

src/components/FileSystem/Polyfill.ts
This problem was caused by the native `DataTransferItem.getAsFileSystemHandle` method returning a real directory handle (because Windows' webview supports the file system access API) but our native build using the virtual implementation. We now always overwrite the method on our native app.
closes #798
=> fix: windows file drop

src-tauri/src/fs_extra.rs, src-tauri/src/main.rs, src/components/Compiler/Worker/TauriFs.ts
Tauri's native `readBinaryFile` API seems to be incredible slow. Implementing our own `read_file` command is 5x faster compared to the previous implementation on our native build.
closes #799
=> upd(Dash): faster file reads

src-tauri/src/fs_extra.rs, src-tauri/src/main.rs, src/components/Compiler/Worker/TauriFs.ts, src/components/FileSystem/Virtual/File.ts, src/components/FileSystem/Virtual/Stores/BaseStore.ts, src/components/FileSystem/Virtual/Stores/TauriFs.ts
Makes pack indexing faster by switching to a custom "File" implementation. This new class defers reading file content until `file.arrayBuffer()`, `file.text()` & friends are called and we only read the last modified timestamp ahead of time.
Depends on #803
=> feat: faster pack indexing

src/utils/getBridgeFolderPath.ts
Since we already require an app reload after selecting a different root folder, we can actually cache the bridge folder for better performance. In our tab saving benchmark, this actually makes saving up to 100ms faster.
Additionally, we avoid weird bugs when a user doesn't restart bridge. after changing the root folder.
=> upd(Tauri): optimize getBridgeFolderPath

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/fs_extra.rs, src-tauri/src/main.rs, src/components/FileSystem/Virtual/File.ts, src/components/FileSystem/Virtual/Stores/BaseStore.ts, src/components/FileSystem/Virtual/Stores/TauriFs.ts, src/utils/loadAsDataUrl.ts
Main issue here was that the web's native `readAsDataUrl()` reader API didn't properly call into our custom VirtualFile class. There's now a `toBlob()` method on our VirtualFile which we can call before passing the virtual file into web APIs. I've also implemented `file.size` & `file.type` to make our implementation (almost) complete
closes #813
=> fix: error upon opening image files

src/components/BedrockWorlds/BlockLibrary/BlockLibrary.ts, src/components/BedrockWorlds/BlockLibrary/loadImage.ts, src/components/Compiler/Worker/FileSystem.ts, src/components/Compiler/Worker/Plugins/CustomComponent/ComponentSchemas.ts, src/components/Editors/HTMLPreview/HTMLPreview.ts, src/components/Extensions/Scripts/JsRuntime.ts, src/components/FileSystem/FileSystem.ts, src/components/FileSystem/FileWatcher.ts, src/components/FileSystem/Virtual/File.ts, src/components/FileSystem/Virtual/Stores/BaseStore.ts, src/components/FileSystem/Virtual/Stores/TauriFs.ts, src/components/ImportFile/BasicFile.ts, src/components/PackIndexer/Worker/LightningCache/LightningCache.ts, src/components/Projects/CreateProject/Files/PackIcon.ts, src/components/Projects/Project/FileChangeRegistry.ts, src/components/TabSystem/FileTab.ts, src/utils/file/moveHandle.ts, src/utils/file/renameHandle.ts, src/utils/loadAsDataUrl.ts
This should fix issues with our virtual file once and for all. The `VirtualFile` class no longer implements all methods from the File interface and therefore also doesn't pretend to be a real file anymore. Due to this change, TypeScript could catch all problematic areas, where we need to be careful passing a VirtualFile to a web API
=> fix: virtual files

src/components/App/Tauri/TauriUpdater.ts, src/components/Sidebar/Sidebar.vue, src/components/TaskManager/Task.ts, src/locales/en.json
This makes the following changes to our update flow on our native app:
- After the user clicks the "Update Available" notification, show a loading task to indicate that work is going on in the background
- When the update is installed successfully, dispose the task and show a new notification to restart the app
=> feat: better update flow

src/components/ContextMenu/ContextMenu.vue, src/components/ContextMenu/List.vue
The context menu positioning doesn't take into account that categories expand on mobile. The easiest way to fix this is to add a fixed height to the context menu and to make it scrollable when expanding sections which is what this PR implements.
https://discord.com/channels/602097536404160523/602097536840237087/1057689226772217946
=> fix: mobile context menu

src/App.ts, src/components/BottomPanel/Terminal/Input.tsx, src/components/Notifications/Errors.ts, src/components/Solid/Inputs/Button/SolidButton.tsx, src/components/Solid/Inputs/IconButton/IconButton.tsx, src/components/Solid/Window/Manager.tsx, src/components/Solid/Window/Window.tsx, src/components/Windows/Error/ErrorWindow.tsx, src/locales/en.json
=> feat: new error window

src/components/PackExplorer/HomeView/SetupView.vue
Resolves #827 by removing the setup card, which tells users to install the native app if they're on a mobile device.  
- Limits the confusion regarding native apps
- Removes possible confusion about project syncing 
- Prevents duplicate install options from being displayed (install the app and native app)
- Run the web app and confirm that the install native app prompt appears
- Enter developer tools for your browser and change the viewport to a mobile device, confirm that the install native app prompt no longer appears
- Confirm that the native app still does not prompt users to install the native app
=> fix: mobile users native app suggestion (#827)

src/components/Extensions/ExtensionLoader.ts, src/components/Notifications/warn.ts, src/locales/en.json
This PR properly handles JSON errors within the extension manifest (emit warning and abort further processing) instead of throwing an error that would subsequently cause infinite loading when opening the extension store.
closes #840
=> fix: extensions infinite loading

src/components/UIElements/DirectoryViewer/ContextMenu/Actions/RevealInFileExplorer.ts
This enables the "Reveal In File Explorer" action to work with arbitrary DirectoryViews. By doing so, the action now also works for com.mojang projects.
=> fix: reveal in file explorer action for com.mojang projects

src/components/Toolbar/Category/project.ts, src/locales/en.json, src/utils/getBridgeFolderPath.ts
Allows quick access to the current bridge. folder without having to select a project first and then navigating a few levels up in the folder hierarchy.
=> feat: view bridge folder

src/App.ts, src/components/OutputFolders/ComMojang/ProjectLoader.ts, src/components/Projects/ProjectChooser/ProjectChooser.ts, src/components/Projects/ProjectManager.ts, src/components/Sidebar/setup.ts
Load com.mojang projects lazily & ahead of time.
Previously, when the user had no bridge. project, they still couldn't access their com.mojang projects. Additionally, opening the project chooser with com.mojang projects now is faster.
=> upd(ComMojang): load projects lazily ahead of time

src/components/Toolbar/Category/project.ts, src/locales/en.json
Allows users to launch Minecraft using the menu action or by pressing `F5`. I think this is a nice convenience feature with little to no maintenance cost.
=> feat: launch minecraft

src-tauri/src/fs_extra.rs
I wrote this code based on the logic of the previous lines in the file, I must note that I know only a bit of Rust. Anyway this works on my machine. Maybe it should be modified to not default the OS to linux when it is unknown, and display some error message or the folder path to be copy/pasted, however I couldn't do that. I hope this help!
=> Add open project folder in linux native app

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs, src-tauri/src/watch.rs, src/App.ts, src/components/ImportFile/BasicFile.ts, src/components/PackIndexer/PackIndexer.ts, src/components/Projects/Project/Project.ts, src/components/Projects/ProjectManager.ts, src/components/TabSystem/TabSystem.ts, src/components/UIElements/DirectoryViewer/ContextMenu/Actions/Edit/Paste.ts
Uses rust to watch for filesystem updates in the selected project, then triggering a project refresh.
This prevents the need to refresh the project when files are modified using external editors.
=> Native: Watches project and reloads project on file changes

package-lock.json, src/components/Projects/CreateProject/ExperimentalGameplay.vue, src/components/Projects/ProjectChooser/ProjectChooser.vue, src/locales/en.json
When a user toggles the HCF experiment an information box will appear letting them know that HCF will be removed in 1.21.20.
HCF is being removed and content using it will break. Bridge. can help spread the word about it's impending removal.
=> Add a warning when turning on HCF that it will be removed soon

package-lock.json, package.json, src/components/Extensions/Scripts/Modules/fs.ts, src/components/FileSystem/Virtual/IDB.ts, src/components/FileSystem/Virtual/Stores/Memory.ts
Fixes #1127, Fixes #1097, Fixes #1095, Fixes #1062, Fixes #1061, Fixes #1040, Fixes #1008
=> Some misc bugfixes to fix Vanilla Pack Viewer on Native
